# Generated by Django 5.1.4 on 2024-12-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("df_goods", "0003_auto_20190427_2158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsinfo",
            name="gpic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="df_goods/image/%Y/%m",
                verbose_name="商品图片",
            ),
        ),
        migrations.AlterField(
            model_name="goodsinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="typeinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
