# Generated by Django 5.1.4 on 2024-12-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("df_user", "0006_auto_20190427_2158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsbrowser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
