# Generated by Django 5.1.4 on 2024-12-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("df_user", "0007_alter_goodsbrowser_id_alter_userinfo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="uemail",
            field=models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
        ),
    ]
